import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@assets/styles/index.scss';
import StoreProvider from '@/redux/StoreProvider';
import Wrapper from '@/layout/wrapper';
import SEO from '@/components/seo';
import HeaderTwo from '@/layout/headers/header-2';
import Footer from '@/layout/footers/footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* <Elements stripe={stripePromise}> */}
          <div id="root">
            <Wrapper>
              <SEO pageTitle="Shop" />
              <HeaderTwo style_2={true} />
              {children}
              <Footer primary_style={true} />
            </Wrapper>
          </div>
          {/* </Elements> */}
          {/* {children} */}
        </body>
      </html>
    </StoreProvider>
  );
}
